site_name: Biaslyze
copyright: Copyright &copy; 2023 Biaslyze
repo_url: https://github.com/biaslyze-dev/biaslyze

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
