site_name: Biaslyze

repo_name: biaslyze
repo_url: https://github.com/biaslyze-dev/biaslyze
copyright: Copyright &copy; 2023 Biaslyze

docs_dir: "docs/sources"

nav:
  - Home: index.md
  - FAQ: faq.md
  - Tutorials:
    - How to identify bias in hate speech detection: tutorials/tutorial-toxic-comments.md
  - API:
    - Bias detectors : 
      - CounterfactualBiasDetector: biaslyze/bias_detectors/counterfactual_biasdetector.md
      - LimeKeywordBiasDetector: biaslyze/bias_detectors/lime_biasdetector.md
    - Results:
      - CounterfactualDetectionResult: biaslyze/results/counterfactual_detection_results.md
      - CounterfactualConceptResult: biaslyze/results/counterfactual_detection_results.md
      - CounterfactualSample: biaslyze/results/counterfactual_detection_results.md
      - LimeDetectionResult: biaslyze/results/lime_detection_results.md
      - LimeSampleResult: biaslyze/results/lime_detection_results.md
    - Concept detectors: biaslyze/concept_detectors.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt

  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate 

  palette: 
    # Palette toggle for light mode
    - scheme: dark
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
