site_name: Biaslyze
site_url: https://biaslyze.org/
site_description: The NLP Bias Identification Toolkit

repo_name: biaslyze
repo_url: https://github.com/biaslyze-dev/biaslyze
copyright: Copyright &copy; 2023 Biaslyze

docs_dir: "docs/sources"

nav:
  - Home: index.md
  - The Algorithm: algorithm.md
  - FAQ: faq.md
  - Tutorials:
    - How to identify bias in hate speech detection: tutorials/tutorial-toxic-comments.md
    - How to work with custom concepts: tutorials/tutorial-working-with-custom-concepts.md
    - How to use counterfactual texts for bias mitigation: tutorials/tutorial-counterfactual-mitigation.md
  - API:
    - Overview: api.md
    - Bias detectors : 
      - CounterfactualBiasDetector: biaslyze/bias_detectors/counterfactual_biasdetector.md
    - Results:
      - CounterfactualDetectionResult: biaslyze/results/counterfactual_detection_results.md
    - Concepts: 
      - Concept: biaslyze/concept_class.md
    - Concept detectors: biaslyze/concept_detectors.md
    - TextRepresentation: biaslyze/text_representation.md
    - Utils: biaslyze/utils.md

theme:
  name: material
  logo: resources/biaslyze_logo_favicon.svg
  favicon: resources/biaslyze_logo_favicon.png
  icon:
    repo: fontawesome/brands/git-alt

  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate 

  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
    - material-plausible
    - social

extra:
  analytics:
    provider: plausible
    domain: biaslyze.org
    #: If using custom domain proxy or self-hosting Plausible,
    #: uncomment and specify script path here:
    # src: "https://plausible.example.com/js/plausible.js"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
