site_name: Biaslyze

repo_name: biaslyze
repo_url: https://github.com/biaslyze-dev/biaslyze
copyright: Copyright &copy; 2023 Biaslyze

docs_dir: "docs/sources"

nav:
  - Home: index.md
  - Getting started:
    - Installation: getting-started.md
  - Ethical considerations: ethics.md
  - Tutorials:
    - Overview: tutorials-overview.md
    - Disaster tweets: tutorials/disaster-tweets.md 
  - API:
    - Overview: api-overview.md
    - Concept detectors: biaslyze/concept_detectors.md
    - Bias detectors : 
      - LimeKeywordBiasDetector: biaslyze/bias_detectors/lime_keyword_biasdetector.md
      - MaskedKeywordBiasDetector: biaslyze/bias_detectors/masked_keyword_biasdetector.md
    - Evaluators: biaslyze/evaluators.md
    - Evaluation results: biaslyze/evaluation_results.md


theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt

  features:
    - content.code.copy
    - navigation.tabs

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
