# dict of concepts with related keywords
CONCEPTS = {
    "nationality": [
        "california",
        "afghanistan",
        "albania",
        "algeria",
        "samoa",
        "andorra",
        "angola",
        "anguilla",
        "antigua",
        "barbuda",
        "argentina",
        "armenia",
        "aruba",
        "australia",
        "austria",
        "azerbaijan",
        "azores",
        "bahrain",
        "bangladesh",
        "barbados",
        "belarus",
        "belgium",
        "belize",
        "benin",
        "bermuda",
        "bhutan",
        "bolivia",
        "bonaire",
        "saba",
        "bosnia-herzegovina",
        "bosnia",
        "herzegovina",
        "botswana",
        "bouvet island",
        "brazil",
        "virgin islands",
        "brunei",
        "bulgaria",
        "burkina faso",
        "burkina",
        "faso",
        "burundi",
        "cambodia",
        "cameroon",
        "canada",
        "cape verde",
        "cayman",
        "central african republic",
        "chad",
        "chile",
        "christmas island",
        "colombia",
        "comoros",
        "congo",
        "cook islands",
        'costa rica',
        "cote d'ivoire",
        "d'ivoire",
        "croatia",
        "cuba",
        "curaçao",
        "cyprus",
        "denmark",
        "djibouti",
        "dominica",
        "ecuador",
        "egypt",
        "salvador",
        "england",
        "guinea",
        "eritrea",
        "estonia",
        "eswatini",
        "ethiopia",
        "falkland",
        "faroe",
        "micronesia",
        "fiji",
        "finland",
        "france",
        "guiana",
        "polynesia",
        "gabon",
        "georgia",
        "germany",
        "ghana",
        "gibraltar",
        "greece",
        "greenland",
        "grenada",
        "guadeloupe",
        "guam",
        "guatemala",
        "guernsey",
        "guinea",
        "guinea-bissau",
        "guyana",
        "haiti",
        "honduras",
        "hong-kong",
        "hong kong",
        "hong",
        "kong",
        "hungary",
        "iceland",
        "india",
        "indonesia",
        "iran",
        "iraq",
        "ireland",
        "isle of man",
        "israel",
        "jamaica",
        "japan",
        "jersey",
        "jordan",
        "kazakhstan",
        "kenya",
        "kiribati",
        "kosovo",
        "kuwait",
        "kyrgyzstan",
        "laos",
        "latvia",
        "lebanon",
        "lesotho",
        "liberia",
        "libya",
        "liechtenstein",
        "lithuania",
        "luxembourg",
        "macau",
        "madagascar",
        "madeira",
        "malawi",
        "malaysia",
        "maldives",
        "mali",
        "malta",
        "marshall islands",
        "martinique",
        "mauritania",
        "mauritius",
        "mayotte",
        "mexico",
        "moldova",
        "monaco",
        "mongolia",
        "montenegro",
        "montserrat",
        "morocco",
        "mozambique",
        "myanmar",
        "namibia",
        "nauru",
        "nepal",
        "netherlands",
        "new caledonia",
        "caledonia",
        "new zealand",
        "zealand",
        "nicaragua",
        "niger",
        "nigeria",
        "niue",
        "norfolk island",
        "norfolk",
        "north korea",
        "north macedonia",
        "northern ireland",
        "northern mariana islands",
        "norway",
        "oman",
        "pakistan",
        "palau",
        "palestine",
        "panama",
        "papua new guinea",
        "papua",
        "paraguay",
        "peru",
        "philippines",
        "pitcairn islands",
        "poland",
        "puerto rico",
        "qatar",
        "republic of the congo",
        "congo",
        "romania",
        "russia",
        "rwanda",
        "réunion",
        "saint barthélemy",
        "saint helena",
        "saint kitts and nevis",
        "saint lucia",
        "saint martin",
        "saint pierre and miquelon",
        "saint vincent",
        "grenadines",
        "samoa",
        "san marino",
        "marino",
        "sark",
        "saudi arabia",
        "arabia",
        "scotland",
        "senegal",
        "seychelles",
        "sierra leone",
        "singapore",
        "sint maarten",
        "slovakia",
        "slovenia",
        "solomon islands",
        "somalia",
        "somaliland",
        "south africa",
        "south georgia and the south sandwich islands",
        "south korea",
        "korea",
        "south sudan",
        "spain",
        "sri lanka",
        "sudan",
        "suriname",
        "svalbard",
        "jan mayen islands",
        "sweden",
        "switzerland",
        "syria",
        "são tomé",
        "príncipe",
        "taiwan",
        "tajikistan",
        "tanzania",
        "thailand",
        "bahamas",
        "gambia",
        "timor-leste",
        "togo",
        "tokelau",
        "tonga",
        "trinidad",
        "tobago",
        "tunisia",
        "turkey",
        "turkmenistan",
        "turks and caicos islands",
        "caicos",
        "tuvalu",
        "uganda",
        "ukraine",
        "united arab emirates",
        "u.a.e.",
        "united kingdom",
        "u.k.",
        "uk",
        "united states minor outlying islands",
        "united states virgin islands",
        "united states of america",
        "u.s.a.",
        "usa",
        "uruguay",
        "uzbekistan",
        "vanuatu",
        "vatican",
        "venezuela",
        "vietnam",
        "wales",
        "wallis",
        "sahara",
        "yemen",
        "zambia",
        "zimbabwe",
        "åland",
        "china",
        "italy",
        "cyprus",
        "portugal",
        "serbia",
        "afghan",
        "albanian",
        "algerian",
        "american",
        "andorran",
        "angolan",
        "antiguans",
        "argentinean",
        "armenian",
        "australian",
        "austrian",
        "azerbaijani",
        "bahamian",
        "bahraini",
        "bangladeshi",
        "barbadian",
        "barbudans",
        "batswana",
        "belarusian",
        "belgian",
        "belizean",
        "beninese",
        "bhutanese",
        "bolivian",
        "bosnian",
        "brazilian",
        "british",
        "bruneian",
        "bulgarian",
        "burkinabe",
        "burmese",
        "burundian",
        "cambodian",
        "cameroonian",
        "canadian",
        "verdean",
        "african",
        "chadian",
        "chilean",
        "chinese",
        "colombian",
        "comoran",
        "congolese",
        "costa",
        "rican",
        "croatian",
        "cuban",
        "cypriot",
        "czech",
        "danish",
        "djibouti",
        "dominican",
        "dutch",
        "timorese",
        "ecuadorean",
        "egyptian",
        "emirian",
        "equatorial",
        "eritrean",
        "estonian",
        "ethiopian",
        "fijian",
        "filipino",
        "finnish",
        "french",
        "gabonese",
        "gambian",
        "georgian",
        "german",
        "ghanaian",
        "greek",
        "grenadian",
        "guatemalan",
        "bissauan",
        "guinean",
        "guyanese",
        "haitian",
        "herzegovinian",
        "honduran",
        "hungarian",
        "icelander",
        "indian",
        "indonesian",
        "iranian",
        "iraqi",
        "irish",
        "israeli",
        "italian",
        "ivorian",
        "jamaican",
        "japanese",
        "jordanian",
        "kazakhstani",
        "kenyan",
        "kittian",
        "nevisian",
        "kuwaiti",
        "kyrgyz",
        "laotian",
        "latvian",
        "lebanese",
        "liberian",
        "libyan",
        "liechtensteiner",
        "lithuanian",
        "luxembourger",
        "macedonian",
        "malagasy",
        "malawian",
        "malaysian",
        "maldivian",
        "malian",
        "maltese",
        "marshallese",
        "mauritanian",
        "mauritian",
        "mexican",
        "micronesian",
        "moldovan",
        "monacan",
        "mongolian",
        "moroccan",
        "mosotho",
        "motswana",
        "mozambican",
        "namibian",
        "nauruan",
        "nepalese",
        "zealander",
        "ni-vanuatu",
        "nicaraguan",
        "nigerian",
        "nigerien",
        "irish",
        "norwegian",
        "omani",
        "pakistani",
        "palauan",
        "panamanian",
        "papua",
        "guinean",
        "paraguayan",
        "peruvian",
        "polish",
        "portuguese",
        "qatari",
        "romanian",
        "russian",
        "rwandan",
        "salvadoran",
        "samoan",
        "marinese",
        "tomean",
        "saudi",
        "scottish",
        "senegalese",
        "serbian",
        "seychellois",
        "leonean",
        "singaporean",
        "slovakian",
        "slovenian",
        "solomon islander",
        "somali",
        "korean",
        "spanish",
        "lankan",
        "sudanese",
        "surinamer",
        "swazi",
        "swedish",
        "swiss",
        "syrian",
        "taiwanese",
        "tajik",
        "tanzanian",
        "thai",
        "togolese",
        "tongan",
        "trinidadian",
        "tobagonian",
        "tunisian",
        "turkish",
        "tuvaluan",
        "ugandan",
        "ukrainian",
        "uruguayan",
        "uzbekistani",
        "venezuelan",
        "vietnamese",
        "welsh",
        "yemenite",
        "zambian",
        "zimbabwean",
    ],
    "ethnicity": [
        "asian",
        "asian indian",
        "african",
        "african-american",
        "afro-caribbean",
        "bangladeshi",
        "black",
        "caucasian",
        "chinese",
        "european",
        "hindu",
        "hispanic",
        "indian",
        "indigenous",
        "irish",
        "native",
        "occidental",
        "oriental",
        "pakistani",
        "south asian",
        "western",
        "white",
        "mixed race",
        "mixed",
    ],
    "religion": [
        "jew",
        "jewish",
        "jews",
        "judaism",
        "muslim",
        "muslims",
        "moslem",
        "moslems",
        "islam",
        "christ",
        "christian",
        "christianity",
        "christians",
        "buddhism",
        "buddhist",
        "buddhists",
    ],
    "gender": [
        {"keyword": "female", "function": ["noun singular", "adjective"], "category": "female"},
        {"keyword": "females", "function": ["noun plural"], "category": "female"},
        {"keyword": "feminine", "function": ["adjective"], "category": "female"},
        {"keyword": "woman", "function": ["noun singular"], "category": "female"},
        {"keyword": "women", "function": ["noun plural"], "category": "female"},
        {"keyword": "she", "function": ["pronoun"], "category": "female"},
        {"keyword": "her", "function": ["pronoun", "possessive pronoun"], "category": "female"},
        {"keyword": "hers", "function": ["possessive pronoun"], "category": "female"},      
        {"keyword": "herself", "function": ["pronoun"], "category": "female"},
        {"keyword": "mrs", "function": ["title", "noun singular"], "category": "female"},
        {"keyword": "ms", "function": ["title", "noun singular"], "category": "female"},
        {"keyword": "miss", "function": ["title", "noun singular"], "category": "female"},
        {"keyword": "madam", "function": ["title", "noun singular"], "category": "female"},
        {"keyword": "lady", "function": ["title", "noun singular"], "category": "female"},
        {"keyword": "ladies", "function": ["possessive noun", "noun plural"], "category": "female"},
        {"keyword": "girl", "function": ["noun singular"], "category": "female"},
        {"keyword": "girls", "function": ["possessive noun", "noun plural"], "category": "female"},
        {"keyword": "mother", "function": ["noun singular"], "category": "female"},
        {"keyword": "mothers", "function": ["possessive noun", "noun plural"], "category": "female"},
        {"keyword": "mom", "function": ["noun singular"], "category": "female"},
        {"keyword": "mommy", "function": ["noun singular"], "category": "female"},
        {"keyword": "mum", "function": ["noun singular"], "category": "female"},
        {"keyword": "mummy", "function": ["noun singular"], "category": "female"},
        {"keyword": "moms", "function": ["possessive noun", "noun plural"], "category": "female"},
        {"keyword": "ma", "function": ["noun singular"], "category": "female"},
        {"keyword": "aunt", "function": ["noun singular"], "category": "female"},
        {"keyword": "daughter", "function": ["noun singular"], "category": "female"},
        {"keyword": "daughters", "function": ["possessive noun", "noun plural"], "category": "female"},
        {"keyword": "wife", "function": ["noun singular"], "category": "female"},
        {"keyword": "wives", "function": ["possessive noun", "noun plural"], "category": "female"},
        {"keyword": "grandmother", "function": ["noun singular"], "category": "female"},
        {"keyword": "grandmothers", "function": ["possessive noun", "noun plural"], "category": "female"},
        {"keyword": "grandma", "function": ["noun singular"], "category": "female"},
        {"keyword": "grandmas", "function": ["possessive noun", "noun plural"], "category": "female"},
        {"keyword": "sister", "function": ["noun singular"], "category": "female"},
        {"keyword": "sisters", "function": ["possessive noun", "noun plural"], "category": "female"},
        {"keyword": "sista", "function": ["noun singular"], "category": "female"},
        {"keyword": "sistas", "function": ["possessive noun", "noun plural"], "category": "female"},
        {"keyword": "male", "function": ["noun singular", "adjective"], "category": "male"},
        {"keyword": "he", "function": ["pronoun"], "category": "male" },
        {"keyword": "him", "function": [ "pronoun"], "category": "male" },
        {"keyword": "his", "function": ["possessive pronoun"], "category": "male" },
        {"keyword": "himself", "function": ["pronoun"], "category": "male"},
        {"keyword": "mr", "function": ["title", "noun singular"], "category": "male"},
        {"keyword": "sir", "function": ["title", "noun singular"], "category": "male"},
        {"keyword": "masculine", "function": ["adjective"], "category": "male"},
        {"keyword": "man", "function": ["noun singular"], "category": "male"},
        {"keyword": "men", "function": ["possessive noun", "noun plural"], "category": "male"},
        {"keyword": "brother", "function": ["noun singular"], "category": "male"},
        {"keyword": "brothers", "function": ["possessive noun", "noun plural"], "category": "male"},
        {"keyword": "bro", "function": ["noun singular"], "category": "male"},
        {"keyword": "bros", "function": ["possessive noun", "noun plural"], "category": "male"},
        {"keyword": "guy", "function": ["noun singular"], "category": "male"},
        {"keyword": "guys", "function": ["possessive noun", "noun plural"], "category": "male"},
        {"keyword": "boy", "function": ["noun singular"], "category": "male"},
        {"keyword": "boys", "function": ["possessive noun", "noun plural"], "category": "male"},
        {"keyword": "father", "function": ["noun singular"], "category": "male"},
        {"keyword": "fathers", "function": ["possessive noun", "noun plural"], "category": "male"},
        {"keyword": "dad", "function": ["noun singular"], "category": "male"},
        {"keyword": "dads", "function": ["possessive noun", "noun plural"], "category": "male"},
        {"keyword": "daddy", "function": ["noun singular"], "category": "male"},
        {"keyword": "daddies", "function": ["possessive noun", "noun plural"], "category": "male"},
        {"keyword": "pa", "function": ["noun singular"], "category": "male"},
        {"keyword": "pas", "function": ["possessive noun", "noun plural"], "category": "male"},
        {"keyword": "son", "function": ["noun singular"], "category": "male"},
        {"keyword": "sons", "function": ["possessive noun", "noun plural"], "category": "male"},
        {"keyword": "husband", "function": ["noun singular"], "category": "male"},
        {"keyword": "husbands", "function": ["possessive noun", "noun plural"], "category": "male"},
        {"keyword": "grandfather", "function": ["noun singular"], "category": "male"},
        {"keyword": "grandfathers", "function": ["possessive noun", "noun plural"], "category": "male"},
        {"keyword": "grandpa", "function": ["noun singular"], "category": "male"},
        {"keyword": "grandpas", "function": ["possessive noun", "noun plural"], "category": "male"},
        {"keyword": "uncle", "function": ["noun singular"], "category": "male"},
        {"keyword": "they", "function": ["pronoun"], "category": "divers"},
        {"keyword": "them", "function": ["pronoun"], "category": "divers"},
        {"keyword": "their", "function": ["possessive pronoun"], "category": "divers"},
        {"keyword": "theirs", "function": ["possessive pronoun"], "category": "divers"},
        {"keyword": "themself", "function": ["pronoun"], "category": "divers"},
        {"keyword": "themselves", "function": ["pronoun"], "category": "divers"},
        {"keyword": "transgender", "function": ["noun singular", "adjective"], "category": "divers"},
        {"keyword": "trans", "function": ["noun singular", "adjective"], "category": "divers"},
    ],
    "gendered words": [
        "waiter",
        "waitress",
        "tailor",
        "seamstress",
        "actor",
        "actress",
        "policeman",
        "policewoman",
        "salesman",
        "saleswoman",
        "benefactor",
        "benefactress",
        "conductor",
        "conductress",
        "steward",
        "stewardess",
        "monk",
        "nun",
        "god",
        "goddess",
    ],
}
