# dict of concepts with related keywords
CONCEPTS = {
    "nationality": [
        {"keyword": "california", "function": ["noun"], "category": "region"},
        {"keyword": "afghanistan", "function": ["noun"], "category": "country"},
        {"keyword": "albania", "function": ["noun"], "category": "country"},
        {"keyword": "algeria", "function": ["noun"], "category": "country"},
        {"keyword": "samoa", "function": ["noun"], "category": "country"},
        {"keyword": "andorra", "function": ["noun"], "category": "country"},
        {"keyword": "angola", "function": ["noun"], "category": "country"},
        {"keyword": "anguilla", "function": ["noun"], "category": "country"},
        {"keyword": "antigua", "function": ["noun"], "category": "country"},
        {"keyword": "barbuda", "function": ["noun"], "category": "country"},
        {"keyword": "argentina", "function": ["noun"], "category": "country"},
        {"keyword": "armenia", "function": ["noun"], "category": "country"},
        {"keyword": "aruba", "function": ["noun"], "category": "country"},
        {"keyword": "australia", "function": ["noun"], "category": "country"},
        {"keyword": "austria", "function": ["noun"], "category": "country"},
        {"keyword": "azerbaijan", "function": ["noun"], "category": "country"},
        {"keyword": "azores", "function": ["noun"], "category": "country"},
        {"keyword": "bahrain", "function": ["noun"], "category": "country"},
        {"keyword": "bangladesh", "function": ["noun"], "category": "country"},
        {"keyword": "barbados", "function": ["noun"], "category": "country"},
        {"keyword": "belarus", "function": ["noun"], "category": "country"},
        {"keyword": "belgium", "function": ["noun"], "category": "country"},
        {"keyword": "belize", "function": ["noun"], "category": "country"},
        {"keyword": "benin", "function": ["noun"], "category": "country"},
        {"keyword": "bermuda", "function": ["noun"], "category": "country"},
        {"keyword": "bhutan", "function": ["noun"], "category": "country"},
        {"keyword": "bolivia", "function": ["noun"], "category": "country"},
        {"keyword": "bonaire", "function": ["noun"], "category": "country"},
        {"keyword": "saba", "function": ["noun"], "category": "country"},
        {"keyword": "bosnia-herzegovina", "function": ["noun"], "category": "country"},
        {"keyword": "bosnia", "function": ["noun"], "category": "country"},
        {"keyword": "herzegovina", "function": ["noun"], "category": "country"},
        {"keyword": "botswana", "function": ["noun"], "category": "country"},
        {"keyword": "bouvet island", "function": ["noun"], "category": "country"},
        {"keyword": "brazil", "function": ["noun"], "category": "country"},
        {"keyword": "virgin islands", "function": ["noun"], "category": "country"},
        {"keyword": "brunei", "function": ["noun"], "category": "country"},
        {"keyword": "bulgaria", "function": ["noun"], "category": "country"},
        {"keyword": "burkina faso", "function": ["noun"], "category": "country"},
        {"keyword": "burkina", "function": ["noun"], "category": "country"},
        {"keyword": "faso", "function": ["noun"], "category": "country"},
        {"keyword": "burundi", "function": ["noun"], "category": "country"},
        {"keyword": "cambodia", "function": ["noun"], "category": "country"},
        {"keyword": "cameroon", "function": ["noun"], "category": "country"},
        {"keyword": "canada", "function": ["noun"], "category": "country"},
        {"keyword": "cape verde", "function": ["noun"], "category": "country"},
        {"keyword": "cayman", "function": ["noun"], "category": "country"},
        {
            "keyword": "central african republic",
            "function": ["noun"],
            "category": "country",
        },
        {"keyword": "chad", "function": ["noun"], "category": "country"},
        {"keyword": "chile", "function": ["noun"], "category": "country"},
        {"keyword": "christmas island", "function": ["noun"], "category": "country"},
        {"keyword": "colombia", "function": ["noun"], "category": "country"},
        {"keyword": "comoros", "function": ["noun"], "category": "country"},
        {"keyword": "congo", "function": ["noun"], "category": "country"},
        {"keyword": "cook islands", "function": ["noun"], "category": "country"},
        {"keyword": 'costa", "rica', "function": ["noun"], "category": "country"},
        {"keyword": "cote d'ivoire", "function": ["noun"], "category": "country"},
        {"keyword": "d'ivoire", "function": ["noun"], "category": "country"},
        {"keyword": "croatia", "function": ["noun"], "category": "country"},
        {"keyword": "cuba", "function": ["noun"], "category": "country"},
        {"keyword": "curaçao", "function": ["noun"], "category": "country"},
        {"keyword": "cyprus", "function": ["noun"], "category": "country"},
        {"keyword": "denmark", "function": ["noun"], "category": "country"},
        {"keyword": "djibouti", "function": ["noun"], "category": "country"},
        {"keyword": "dominica", "function": ["noun"], "category": "country"},
        {"keyword": "ecuador", "function": ["noun"], "category": "country"},
        {"keyword": "egypt", "function": ["noun"], "category": "country"},
        {"keyword": "salvador", "function": ["noun"], "category": "country"},
        {"keyword": "england", "function": ["noun"], "category": "country"},
        {"keyword": "guinea", "function": ["noun"], "category": "country"},
        {"keyword": "eritrea", "function": ["noun"], "category": "country"},
        {"keyword": "estonia", "function": ["noun"], "category": "country"},
        {"keyword": "eswatini", "function": ["noun"], "category": "country"},
        {"keyword": "ethiopia", "function": ["noun"], "category": "country"},
        {"keyword": "falkland", "function": ["noun"], "category": "country"},
        {"keyword": "faroe", "function": ["noun"], "category": "country"},
        {"keyword": "micronesia", "function": ["noun"], "category": "country"},
        {"keyword": "fiji", "function": ["noun"], "category": "country"},
        {"keyword": "finland", "function": ["noun"], "category": "country"},
        {"keyword": "france", "function": ["noun"], "category": "country"},
        {"keyword": "guiana", "function": ["noun"], "category": "country"},
        {"keyword": "polynesia", "function": ["noun"], "category": "country"},
        {"keyword": "gabon", "function": ["noun"], "category": "country"},
        {"keyword": "georgia", "function": ["noun"], "category": "country"},
        {"keyword": "germany", "function": ["noun"], "category": "country"},
        {"keyword": "ghana", "function": ["noun"], "category": "country"},
        {"keyword": "gibraltar", "function": ["noun"], "category": "country"},
        {"keyword": "greece", "function": ["noun"], "category": "country"},
        {"keyword": "greenland", "function": ["noun"], "category": "country"},
        {"keyword": "grenada", "function": ["noun"], "category": "country"},
        {"keyword": "guadeloupe", "function": ["noun"], "category": "country"},
        {"keyword": "guam", "function": ["noun"], "category": "country"},
        {"keyword": "guatemala", "function": ["noun"], "category": "country"},
        {"keyword": "guernsey", "function": ["noun"], "category": "country"},
        {"keyword": "guinea", "function": ["noun"], "category": "country"},
        {"keyword": "guinea-bissau", "function": ["noun"], "category": "country"},
        {"keyword": "guyana", "function": ["noun"], "category": "country"},
        {"keyword": "haiti", "function": ["noun"], "category": "country"},
        {"keyword": "honduras", "function": ["noun"], "category": "country"},
        {"keyword": "hong-kong", "function": ["noun"], "category": "country"},
        {"keyword": "hong kong", "function": ["noun"], "category": "country"},
        {"keyword": "hong", "function": ["noun"], "category": "country"},
        {"keyword": "kong", "function": ["noun"], "category": "country"},
        {"keyword": "hungary", "function": ["noun"], "category": "country"},
        {"keyword": "iceland", "function": ["noun"], "category": "country"},
        {"keyword": "india", "function": ["noun"], "category": "country"},
        {"keyword": "indonesia", "function": ["noun"], "category": "country"},
        {"keyword": "iran", "function": ["noun"], "category": "country"},
        {"keyword": "iraq", "function": ["noun"], "category": "country"},
        {"keyword": "ireland", "function": ["noun"], "category": "country"},
        {"keyword": "isle of man", "function": ["noun"], "category": "country"},
        {"keyword": "israel", "function": ["noun"], "category": "country"},
        {"keyword": "jamaica", "function": ["noun"], "category": "country"},
        {"keyword": "japan", "function": ["noun"], "category": "country"},
        {"keyword": "jersey", "function": ["noun"], "category": "country"},
        {"keyword": "jordan", "function": ["noun"], "category": "country"},
        {"keyword": "kazakhstan", "function": ["noun"], "category": "country"},
        {"keyword": "kenya", "function": ["noun"], "category": "country"},
        {"keyword": "kiribati", "function": ["noun"], "category": "country"},
        {"keyword": "kosovo", "function": ["noun"], "category": "country"},
        {"keyword": "kuwait", "function": ["noun"], "category": "country"},
        {"keyword": "kyrgyzstan", "function": ["noun"], "category": "country"},
        {"keyword": "laos", "function": ["noun"], "category": "country"},
        {"keyword": "latvia", "function": ["noun"], "category": "country"},
        {"keyword": "lebanon", "function": ["noun"], "category": "country"},
        {"keyword": "lesotho", "function": ["noun"], "category": "country"},
        {"keyword": "liberia", "function": ["noun"], "category": "country"},
        {"keyword": "libya", "function": ["noun"], "category": "country"},
        {"keyword": "liechtenstein", "function": ["noun"], "category": "country"},
        {"keyword": "lithuania", "function": ["noun"], "category": "country"},
        {"keyword": "luxembourg", "function": ["noun"], "category": "country"},
        {"keyword": "macau", "function": ["noun"], "category": "country"},
        {"keyword": "madagascar", "function": ["noun"], "category": "country"},
        {"keyword": "madeira", "function": ["noun"], "category": "country"},
        {"keyword": "malawi", "function": ["noun"], "category": "country"},
        {"keyword": "malaysia", "function": ["noun"], "category": "country"},
        {"keyword": "maldives", "function": ["noun"], "category": "country"},
        {"keyword": "mali", "function": ["noun"], "category": "country"},
        {"keyword": "malta", "function": ["noun"], "category": "country"},
        {"keyword": "marshall islands", "function": ["noun"], "category": "country"},
        {"keyword": "martinique", "function": ["noun"], "category": "country"},
        {"keyword": "mauritania", "function": ["noun"], "category": "country"},
        {"keyword": "mauritius", "function": ["noun"], "category": "country"},
        {"keyword": "mayotte", "function": ["noun"], "category": "country"},
        {"keyword": "mexico", "function": ["noun"], "category": "country"},
        {"keyword": "moldova", "function": ["noun"], "category": "country"},
        {"keyword": "monaco", "function": ["noun"], "category": "country"},
        {"keyword": "mongolia", "function": ["noun"], "category": "country"},
        {"keyword": "montenegro", "function": ["noun"], "category": "country"},
        {"keyword": "montserrat", "function": ["noun"], "category": "country"},
        {"keyword": "morocco", "function": ["noun"], "category": "country"},
        {"keyword": "mozambique", "function": ["noun"], "category": "country"},
        {"keyword": "myanmar", "function": ["noun"], "category": "country"},
        {"keyword": "namibia", "function": ["noun"], "category": "country"},
        {"keyword": "nauru", "function": ["noun"], "category": "country"},
        {"keyword": "nepal", "function": ["noun"], "category": "country"},
        {"keyword": "netherlands", "function": ["noun"], "category": "country"},
        {"keyword": "new caledonia", "function": ["noun"], "category": "country"},
        {"keyword": "caledonia", "function": ["noun"], "category": "country"},
        {"keyword": "new zealand", "function": ["noun"], "category": "country"},
        {"keyword": "zealand", "function": ["noun"], "category": "country"},
        {"keyword": "nicaragua", "function": ["noun"], "category": "country"},
        {"keyword": "niger", "function": ["noun"], "category": "country"},
        {"keyword": "nigeria", "function": ["noun"], "category": "country"},
        {"keyword": "niue", "function": ["noun"], "category": "country"},
        {"keyword": "norfolk island", "function": ["noun"], "category": "country"},
        {"keyword": "norfolk", "function": ["noun"], "category": "country"},
        {"keyword": "north korea", "function": ["noun"], "category": "country"},
        {"keyword": "north macedonia", "function": ["noun"], "category": "country"},
        {"keyword": "northern ireland", "function": ["noun"], "category": "country"},
        {
            "keyword": "northern mariana islands",
            "function": ["noun"],
            "category": "country",
        },
        {"keyword": "norway", "function": ["noun"], "category": "country"},
        {"keyword": "oman", "function": ["noun"], "category": "country"},
        {"keyword": "pakistan", "function": ["noun"], "category": "country"},
        {"keyword": "palau", "function": ["noun"], "category": "country"},
        {"keyword": "palestine", "function": ["noun"], "category": "country"},
        {"keyword": "panama", "function": ["noun"], "category": "country"},
        {"keyword": "papua new guinea", "function": ["noun"], "category": "country"},
        {"keyword": "papua", "function": ["noun"], "category": "country"},
        {"keyword": "paraguay", "function": ["noun"], "category": "country"},
        {"keyword": "peru", "function": ["noun"], "category": "country"},
        {"keyword": "philippines", "function": ["noun"], "category": "country"},
        {"keyword": "pitcairn islands", "function": ["noun"], "category": "country"},
        {"keyword": "poland", "function": ["noun"], "category": "country"},
        {"keyword": "puerto rico", "function": ["noun"], "category": "country"},
        {"keyword": "qatar", "function": ["noun"], "category": "country"},
        {
            "keyword": "republic of the congo",
            "function": ["noun"],
            "category": "country",
        },
        {"keyword": "congo", "function": ["noun"], "category": "country"},
        {"keyword": "romania", "function": ["noun"], "category": "country"},
        {"keyword": "russia", "function": ["noun"], "category": "country"},
        {"keyword": "rwanda", "function": ["noun"], "category": "country"},
        {"keyword": "réunion", "function": ["noun"], "category": "country"},
        {"keyword": "saint barthélemy", "function": ["noun"], "category": "country"},
        {"keyword": "saint helena", "function": ["noun"], "category": "country"},
        {
            "keyword": "saint kitts and nevis",
            "function": ["noun"],
            "category": "country",
        },
        {"keyword": "saint lucia", "function": ["noun"], "category": "country"},
        {"keyword": "saint martin", "function": ["noun"], "category": "country"},
        {
            "keyword": "saint pierre and miquelon",
            "function": ["noun"],
            "category": "country",
        },
        {
            "keyword": "saint vincent",
            "function": ["noun"],
            "category": "country",
        },
        {
            "keyword": "grenadines",
            "function": ["noun"],
            "category": "country",
        },
        {"keyword": "san marino", "function": ["noun"], "category": "country"},
        {"keyword": "marino", "function": ["noun"], "category": "country"},
        {"keyword": "sark", "function": ["noun"], "category": "country"},
        {"keyword": "saudi arabia", "function": ["noun"], "category": "country"},
        {"keyword": "arabia", "function": ["noun"], "category": "country"},
        {"keyword": "scotland", "function": ["noun"], "category": "country"},
        {"keyword": "senegal", "function": ["noun"], "category": "country"},
        {"keyword": "seychelles", "function": ["noun"], "category": "country"},
        {"keyword": "sierra leone", "function": ["noun"], "category": "country"},
        {"keyword": "singapore", "function": ["noun"], "category": "country"},
        {"keyword": "sint maarten", "function": ["noun"], "category": "country"},
        {"keyword": "slovakia", "function": ["noun"], "category": "country"},
        {"keyword": "slovenia", "function": ["noun"], "category": "country"},
        {"keyword": "solomon islands", "function": ["noun"], "category": "country"},
        {"keyword": "somalia", "function": ["noun"], "category": "country"},
        {"keyword": "somaliland", "function": ["noun"], "category": "country"},
        {"keyword": "south africa", "function": ["noun"], "category": "country"},
        {
            "keyword": "south georgia and the south sandwich islands",
            "function": ["noun"],
            "category": "country",
        },
        {"keyword": "south korea", "function": ["noun"], "category": "country"},
        {"keyword": "korea", "function": ["noun"], "category": "country"},
        {"keyword": "south sudan", "function": ["noun"], "category": "country"},
        {"keyword": "spain", "function": ["noun"], "category": "country"},
        {"keyword": "sri lanka", "function": ["noun"], "category": "country"},
        {"keyword": "sudan", "function": ["noun"], "category": "country"},
        {"keyword": "suriname", "function": ["noun"], "category": "country"},
        {
            "keyword": "jan mayen islands",
            "function": ["noun"],
            "category": "country",
        },
        {
            "keyword": "svalbard",
            "function": ["noun"],
            "category": "country",
        },
        {"keyword": "sweden", "function": ["noun"], "category": "country"},
        {"keyword": "switzerland", "function": ["noun"], "category": "country"},
        {"keyword": "syria", "function": ["noun"], "category": "country"},
        {
            "keyword": "são tomé",
            "function": ["noun"],
            "category": "country",
        },
        {
            "keyword": "príncipe",
            "function": ["noun"],
            "category": "country",
        },
        {"keyword": "taiwan", "function": ["noun"], "category": "country"},
        {"keyword": "tajikistan", "function": ["noun"], "category": "country"},
        {"keyword": "tanzania", "function": ["noun"], "category": "country"},
        {"keyword": "thailand", "function": ["noun"], "category": "country"},
        {"keyword": "bahamas", "function": ["noun"], "category": "country"},
        {"keyword": "gambia", "function": ["noun"], "category": "country"},
        {"keyword": "timor-leste", "function": ["noun"], "category": "country"},
        {"keyword": "togo", "function": ["noun"], "category": "country"},
        {"keyword": "tokelau", "function": ["noun"], "category": "country"},
        {"keyword": "tonga", "function": ["noun"], "category": "country"},
        {"keyword": "trinidad", "function": ["noun"], "category": "country"},
        {"keyword": "tobago", "function": ["noun"], "category": "country"},
        {"keyword": "tunisia", "function": ["noun"], "category": "country"},
        {"keyword": "turkey", "function": ["noun"], "category": "country"},
        {"keyword": "turkmenistan", "function": ["noun"], "category": "country"},
        {
            "keyword": "turks and caicos islands",
            "function": ["noun"],
            "category": "country",
        },
        {"keyword": "caicos", "function": ["noun"], "category": "country"},
        {"keyword": "tuvalu", "function": ["noun"], "category": "country"},
        {"keyword": "uganda", "function": ["noun"], "category": "country"},
        {"keyword": "ukraine", "function": ["noun"], "category": "country"},
        {
            "keyword": "united arab emirates",
            "function": ["noun"],
            "category": "country",
        },
        {"keyword": "u.a.e.", "function": ["noun"], "category": "country"},
        {"keyword": "united kingdom", "function": ["noun"], "category": "country"},
        {"keyword": "u.k.", "function": ["noun"], "category": "country"},
        {"keyword": "uk", "function": ["noun"], "category": "country"},
        {
            "keyword": "united states minor outlying islands",
            "function": ["noun"],
            "category": "country",
        },
        {
            "keyword": "united states virgin islands",
            "function": ["noun"],
            "category": "country",
        },
        {
            "keyword": "united states of america",
            "function": ["noun"],
            "category": "country",
        },
        {"keyword": "u.s.a.", "function": ["noun"], "category": "country"},
        {"keyword": "usa", "function": ["noun"], "category": "country"},
        {"keyword": "uruguay", "function": ["noun"], "category": "country"},
        {"keyword": "uzbekistan", "function": ["noun"], "category": "country"},
        {"keyword": "vanuatu", "function": ["noun"], "category": "country"},
        {"keyword": "vatican", "function": ["noun"], "category": "country"},
        {"keyword": "venezuela", "function": ["noun"], "category": "country"},
        {"keyword": "vietnam", "function": ["noun"], "category": "country"},
        {"keyword": "wales", "function": ["noun"], "category": "country"},
        {"keyword": "wallis", "function": ["noun"], "category": "country"},
        {"keyword": "sahara", "function": ["noun"], "category": "country"},
        {"keyword": "yemen", "function": ["noun"], "category": "country"},
        {"keyword": "zambia", "function": ["noun"], "category": "country"},
        {"keyword": "zimbabwe", "function": ["noun"], "category": "country"},
        {"keyword": "åland", "function": ["noun"], "category": "country"},
        {"keyword": "china", "function": ["noun"], "category": "country"},
        {"keyword": "italy", "function": ["noun"], "category": "country"},
        {"keyword": "cyprus", "function": ["noun"], "category": "country"},
        {"keyword": "portugal", "function": ["noun"], "category": "country"},
        {"keyword": "serbia", "function": ["noun"], "category": "country"},
        {"keyword": "europa", "function": ["noun"], "category": "continent"},
        {"keyword": "european", "function": ["noun"], "category": "nationality"},
        {"keyword": "asia", "function": ["noun"], "category": "continent"},
        {"keyword": "asian", "function": ["noun"], "category": "nationality"},
        {
            "keyword": "afghan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "albanian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "algerian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "american",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "andorran",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "angolan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "antiguans",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "argentinean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "armenian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "australian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "austrian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "azerbaijani",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "bahamian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "bahraini",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "bangladeshi",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "barbadian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "barbudans",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "batswana",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "belarusian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "belgian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "belizean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "beninese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "bhutanese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "bolivian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "bosnian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "brazilian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "british",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "bruneian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "bulgarian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "burkinabe",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "burmese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "burundian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "cambodian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "cameroonian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "canadian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "verdean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "african",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "chadian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "chilean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "chinese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "colombian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "comoran",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "congolese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "costa",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "rican",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "croatian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "cuban",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "cypriot",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "czech",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "danish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "djibouti",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "dominican",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "dutch",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "timorese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "ecuadorean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "egyptian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "english",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "emirian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "equatorial",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "eritrean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "estonian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "ethiopian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "fijian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "filipino",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "finnish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "french",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "gabonese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "gambian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "georgian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "german",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "ghanaian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "greek",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "grenadian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "guatemalan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "bissauan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "guinean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "guyanese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "haitian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "herzegovinian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "honduran",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "hungarian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "icelander",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "indian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "indonesian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "iranian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "iraqi",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "irish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "israeli",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "italian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "ivorian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "jamaican",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "japanese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "jordanian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "kazakhstani",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "kenyan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "kittian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "nevisian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "kuwaiti",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "kyrgyz",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "laotian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "latvian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "lebanese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "liberian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "libyan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "liechtensteiner",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "lithuanian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "luxembourger",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "macedonian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "malagasy",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "malawian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "malaysian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "maldivian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "malian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "maltese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "marshallese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "mauritanian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "mauritian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "mexican",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "micronesian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "moldovan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "monacan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "mongolian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "moroccan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "mosotho",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "motswana",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "mozambican",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "namibian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "nauruan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "nepalese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "zealander",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "ni-vanuatu",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "nicaraguan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "nigerian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "nigerien",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "irish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "norwegian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "omani",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "pakistani",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "palauan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "panamanian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "papua",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "guinean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "paraguayan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "peruvian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "polish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "portuguese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "qatari",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "romanian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "russian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "rwandan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "salvadoran",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "samoan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "marinese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "tomean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "saudi",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "scottish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "senegalese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "serbian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "seychellois",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "leonean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "singaporean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "slovakian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "slovenian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "solomon islander",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "somali",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "korean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "spanish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "lankan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "sudanese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "surinamer",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "swazi",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "swedish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "swiss",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "syrian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "taiwanese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "tajik",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "tanzanian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "thai",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "togolese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "tongan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "trinidadian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "tobagonian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "tunisian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "turkish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "tuvaluan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "ugandan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "ukrainian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "uruguayan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "uzbekistani",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "venezuelan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "vietnamese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "welsh",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "yemenite",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyword": "zambian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
    ],
    "ethnicity": [
        {"keyword": "asian", "function": ["noun", "adjective"]},
        {"keyword": "asian indian", "function": ["noun", "adjective"]},
        {"keyword": "african", "function": ["noun", "adjective"]},
        {"keyword": "african-american", "function": ["noun", "adjective"]},
        {"keyword": "afro-caribbean", "function": ["noun", "adjective"]},
        {"keyword": "bangladeshi", "function": ["noun", "adjective"]},
        {"keyword": "black", "function": ["noun", "adjective"]},
        {"keyword": "caucasian", "function": ["noun", "adjective"]},
        {"keyword": "chinese", "function": ["noun", "adjective"]},
        {"keyword": "european", "function": ["noun", "adjective"]},
        {"keyword": "hindu", "function": ["noun", "adjective"]},
        {"keyword": "hispanic", "function": ["noun", "adjective"]},
        {"keyword": "indian", "function": ["noun", "adjective"]},
        {"keyword": "indigenous", "function": ["noun", "adjective"]},
        {"keyword": "irish", "function": ["noun", "adjective"]},
        {"keyword": "native", "function": ["noun", "adjective"]},
        {"keyword": "occidental", "function": ["noun", "adjective"]},
        {"keyword": "oriental", "function": ["noun", "adjective"]},
        {"keyword": "pakistani", "function": ["noun", "adjective"]},
        {"keyword": "south asian", "function": ["noun", "adjective"]},
        {"keyword": "western", "function": ["noun", "adjective"]},
        {"keyword": "white", "function": ["noun", "adjective"]},
        {"keyword": "mixed race", "function": ["noun", "adjective"]},
        {"keyword": "mixed", "function": ["noun", "adjective"]},
    ],
    "religion": [
        {"keyword": "jew", "function": ["noun_singular"], "category": "judaism"},
        {"keyword": "jewish", "function": ["adjective"], "category": "judaism"},
        {"keyword": "jews", "function": ["noun_plural"], "category": "judaism"},
        {"keyword": "judaism", "function": ["noun_singular"], "category": "judaism"},
        {
            "keyword": "muslim",
            "function": ["noun_singular", "adjective"],
            "category": "islam",
        },
        {"keyword": "muslims", "function": ["noun_plural"], "category": "islam"},
        {"keyword": "moslem", "function": ["noun_singular"], "category": "islam"},
        {"keyword": "moslems", "function": ["noun_plural"], "category": "islam"},
        {"keyword": "islam", "function": ["noun"], "category": "islam"},
        {
            "keyword": "christ",
            "function": ["noun_singular"],
            "category": "christianity",
        },
        {
            "keyword": "christian",
            "function": ["noun_singular"],
            "category": "christianity",
        },
        {"keyword": "christianity", "function": ["noun"], "category": "christianity"},
        {
            "keyword": "christians",
            "function": ["noun_plural"],
            "category": "christianity",
        },
        {"keyword": "buddhism", "function": ["noun"], "category": "buddhism"},
        {"keyword": "buddhist", "function": ["noun_singular"], "category": "buddhism"},
        {"keyword": "buddhists", "function": ["noun_plural"], "category": "buddhism"},
        {"keyword": "hindu", "function": ["noun_singular"], "category": "hinduism"},
        {"keyword": "hindus", "function": ["noun_plural"], "category": "hinduism"},
        {"keyword": "hinduism", "function": ["noun"], "category": "hinduism"},
    ],
    "gender": [
        {
            "keyword": "female",
            "function": ["noun singular", "adjective"],
            "category": "female",
        },
        {"keyword": "females", "function": ["noun plural"], "category": "female"},
        {"keyword": "feminine", "function": ["adjective"], "category": "female"},
        {"keyword": "woman", "function": ["noun singular"], "category": "female"},
        {"keyword": "women", "function": ["noun plural"], "category": "female"},
        {"keyword": "she", "function": ["pronoun"], "category": "female"},
        {
            "keyword": "her",
            "function": ["pronoun", "possessive pronoun"],
            "category": "female",
        },
        {"keyword": "hers", "function": ["possessive pronoun"], "category": "female"},
        {"keyword": "herself", "function": ["pronoun"], "category": "female"},
        {
            "keyword": "mrs",
            "function": ["title", "noun singular"],
            "category": "female",
        },
        {"keyword": "ms", "function": ["title", "noun singular"], "category": "female"},
        {
            "keyword": "miss",
            "function": ["title", "noun singular"],
            "category": "female",
        },
        {
            "keyword": "madam",
            "function": ["title", "noun singular"],
            "category": "female",
        },
        {
            "keyword": "lady",
            "function": ["title", "noun singular"],
            "category": "female",
        },
        {
            "keyword": "ladies",
            "function": ["possessive noun", "noun plural"],
            "category": "female",
        },
        {"keyword": "girl", "function": ["noun singular"], "category": "female"},
        {
            "keyword": "girls",
            "function": ["possessive noun", "noun plural"],
            "category": "female",
        },
        {"keyword": "mother", "function": ["noun singular"], "category": "female"},
        {
            "keyword": "mothers",
            "function": ["possessive noun", "noun plural"],
            "category": "female",
        },
        {"keyword": "mom", "function": ["noun singular"], "category": "female"},
        {"keyword": "mommy", "function": ["noun singular"], "category": "female"},
        {"keyword": "mum", "function": ["noun singular"], "category": "female"},
        {"keyword": "mummy", "function": ["noun singular"], "category": "female"},
        {
            "keyword": "moms",
            "function": ["possessive noun", "noun plural"],
            "category": "female",
        },
        {"keyword": "ma", "function": ["noun singular"], "category": "female"},
        {"keyword": "aunt", "function": ["noun singular"], "category": "female"},
        {"keyword": "daughter", "function": ["noun singular"], "category": "female"},
        {
            "keyword": "daughters",
            "function": ["possessive noun", "noun plural"],
            "category": "female",
        },
        {"keyword": "wife", "function": ["noun singular"], "category": "female"},
        {
            "keyword": "wives",
            "function": ["possessive noun", "noun plural"],
            "category": "female",
        },
        {"keyword": "grandmother", "function": ["noun singular"], "category": "female"},
        {
            "keyword": "grandmothers",
            "function": ["possessive noun", "noun plural"],
            "category": "female",
        },
        {"keyword": "grandma", "function": ["noun singular"], "category": "female"},
        {
            "keyword": "grandmas",
            "function": ["possessive noun", "noun plural"],
            "category": "female",
        },
        {"keyword": "sister", "function": ["noun singular"], "category": "female"},
        {
            "keyword": "sisters",
            "function": ["possessive noun", "noun plural"],
            "category": "female",
        },
        {"keyword": "sista", "function": ["noun singular"], "category": "female"},
        {
            "keyword": "sistas",
            "function": ["possessive noun", "noun plural"],
            "category": "female",
        },
        {
            "keyword": "male",
            "function": ["noun singular", "adjective"],
            "category": "male",
        },
        {"keyword": "he", "function": ["pronoun"], "category": "male"},
        {"keyword": "him", "function": ["pronoun"], "category": "male"},
        {"keyword": "his", "function": ["possessive pronoun"], "category": "male"},
        {"keyword": "himself", "function": ["pronoun"], "category": "male"},
        {"keyword": "mr", "function": ["title", "noun singular"], "category": "male"},
        {"keyword": "sir", "function": ["title", "noun singular"], "category": "male"},
        {"keyword": "masculine", "function": ["adjective"], "category": "male"},
        {"keyword": "man", "function": ["noun singular"], "category": "male"},
        {
            "keyword": "men",
            "function": ["possessive noun", "noun plural"],
            "category": "male",
        },
        {"keyword": "brother", "function": ["noun singular"], "category": "male"},
        {
            "keyword": "brothers",
            "function": ["possessive noun", "noun plural"],
            "category": "male",
        },
        {"keyword": "bro", "function": ["noun singular"], "category": "male"},
        {
            "keyword": "bros",
            "function": ["possessive noun", "noun plural"],
            "category": "male",
        },
        {"keyword": "guy", "function": ["noun singular"], "category": "male"},
        {
            "keyword": "guys",
            "function": ["possessive noun", "noun plural"],
            "category": "male",
        },
        {"keyword": "boy", "function": ["noun singular"], "category": "male"},
        {
            "keyword": "boys",
            "function": ["possessive noun", "noun plural"],
            "category": "male",
        },
        {"keyword": "father", "function": ["noun singular"], "category": "male"},
        {
            "keyword": "fathers",
            "function": ["possessive noun", "noun plural"],
            "category": "male",
        },
        {"keyword": "dad", "function": ["noun singular"], "category": "male"},
        {
            "keyword": "dads",
            "function": ["possessive noun", "noun plural"],
            "category": "male",
        },
        {"keyword": "daddy", "function": ["noun singular"], "category": "male"},
        {
            "keyword": "daddies",
            "function": ["possessive noun", "noun plural"],
            "category": "male",
        },
        {"keyword": "pa", "function": ["noun singular"], "category": "male"},
        {
            "keyword": "pas",
            "function": ["possessive noun", "noun plural"],
            "category": "male",
        },
        {"keyword": "son", "function": ["noun singular"], "category": "male"},
        {
            "keyword": "sons",
            "function": ["possessive noun", "noun plural"],
            "category": "male",
        },
        {"keyword": "husband", "function": ["noun singular"], "category": "male"},
        {
            "keyword": "husbands",
            "function": ["possessive noun", "noun plural"],
            "category": "male",
        },
        {"keyword": "grandfather", "function": ["noun singular"], "category": "male"},
        {
            "keyword": "grandfathers",
            "function": ["possessive noun", "noun plural"],
            "category": "male",
        },
        {"keyword": "grandpa", "function": ["noun singular"], "category": "male"},
        {
            "keyword": "grandpas",
            "function": ["possessive noun", "noun plural"],
            "category": "male",
        },
        {"keyword": "uncle", "function": ["noun singular"], "category": "male"},
        {"keyword": "they", "function": ["pronoun"], "category": "divers"},
        {"keyword": "them", "function": ["pronoun"], "category": "divers"},
        {"keyword": "their", "function": ["possessive pronoun"], "category": "divers"},
        {"keyword": "theirs", "function": ["possessive pronoun"], "category": "divers"},
        {"keyword": "themself", "function": ["pronoun"], "category": "divers"},
        {"keyword": "themselves", "function": ["pronoun"], "category": "divers"},
        {
            "keyword": "transgender",
            "function": ["noun singular", "adjective"],
            "category": "divers",
        },
        {
            "keyword": "trans",
            "function": ["noun singular", "adjective"],
            "category": "divers",
        },
    ],
    "gendered words": [
        {"keyword": "waiter", "function": ["noun_singular"], "category": "male"},
        {"keyword": "waitress", "function": ["noun_singular"], "category": "female"},
        {"keyword": "tailor", "function": ["noun_singular"], "category": "male"},
        {"keyword": "seamstress", "function": ["noun_singular"], "category": "female"},
        {"keyword": "actor", "function": ["noun_singular"], "category": "male"},
        {"keyword": "actress", "function": ["noun_singular"], "category": "female"},
        {"keyword": "policeman", "function": ["noun_singular"], "category": "male"},
        {"keyword": "policewoman", "function": ["noun_singular"], "category": "female"},
        {"keyword": "salesman", "function": ["noun_singular"], "category": "male"},
        {"keyword": "saleswoman", "function": ["noun_singular"], "category": "female"},
        {"keyword": "benefactor", "function": ["noun_singular"], "category": "male"},
        {
            "keyword": "benefactress",
            "function": ["noun_singular"],
            "category": "female",
        },
        {"keyword": "conductor", "function": ["noun_singular"], "category": "male"},
        {"keyword": "conductress", "function": ["noun_singular"], "category": "female"},
        {"keyword": "steward", "function": ["noun_singular"], "category": "male"},
        {"keyword": "stewardess", "function": ["noun_singular"], "category": "female"},
        {"keyword": "monk", "function": ["noun_singular"], "category": "male"},
        {"keyword": "nun", "function": ["noun_singular"], "category": "female"},
        {"keyword": "god", "function": ["noun_singular"], "category": "male"},
        {"keyword": "goddess", "function": ["noun_singular"], "category": "female"},
    ],
}
