# dict of concepts with related keywords
CONCEPTS = {
    "nationality": [
        {"keyword": "california", "function": ["noun"], "category": "region"},
        {"keyowrd": "afghanistan", "function": ["noun"], "category": "country"},
        {"keyowrd": "albania", "function": ["noun"], "category": "country"},
        {"keyowrd": "algeria", "function": ["noun"], "category": "country"},
        {"keyowrd": "samoa", "function": ["noun"], "category": "country"},
        {"keyowrd": "andorra", "function": ["noun"], "category": "country"},
        {"keyowrd": "angola", "function": ["noun"], "category": "country"},
        {"keyowrd": "anguilla", "function": ["noun"], "category": "country"},
        {"keyowrd": "antigua", "function": ["noun"], "category": "country"},
        {"keyowrd": "barbuda", "function": ["noun"], "category": "country"},
        {"keyowrd": "argentina", "function": ["noun"], "category": "country"},
        {"keyowrd": "armenia", "function": ["noun"], "category": "country"},
        {"keyowrd": "aruba", "function": ["noun"], "category": "country"},
        {"keyowrd": "australia", "function": ["noun"], "category": "country"},
        {"keyowrd": "austria", "function": ["noun"], "category": "country"},
        {"keyowrd": "azerbaijan", "function": ["noun"], "category": "country"},
        {"keyowrd": "azores", "function": ["noun"], "category": "country"},
        {"keyowrd": "bahrain", "function": ["noun"], "category": "country"},
        {"keyowrd": "bangladesh", "function": ["noun"], "category": "country"},
        {"keyowrd": "barbados", "function": ["noun"], "category": "country"},
        {"keyowrd": "belarus", "function": ["noun"], "category": "country"},
        {"keyowrd": "belgium", "function": ["noun"], "category": "country"},
        {"keyowrd": "belize", "function": ["noun"], "category": "country"},
        {"keyowrd": "benin", "function": ["noun"], "category": "country"},
        {"keyowrd": "bermuda", "function": ["noun"], "category": "country"},
        {"keyowrd": "bhutan", "function": ["noun"], "category": "country"},
        {"keyowrd": "bolivia", "function": ["noun"], "category": "country"},
        {"keyowrd": "bonaire", "function": ["noun"], "category": "country"},
        {"keyowrd": "saba", "function": ["noun"], "category": "country"},
        {"keyowrd": "bosnia-herzegovina", "function": ["noun"], "category": "country"},
        {"keyowrd": "bosnia", "function": ["noun"], "category": "country"},
        {"keyowrd": "herzegovina", "function": ["noun"], "category": "country"},
        {"keyowrd": "botswana", "function": ["noun"], "category": "country"},
        {"keyowrd": "bouvet island", "function": ["noun"], "category": "country"},
        {"keyowrd": "brazil", "function": ["noun"], "category": "country"},
        {"keyowrd": "virgin islands", "function": ["noun"], "category": "country"},
        {"keyowrd": "brunei", "function": ["noun"], "category": "country"},
        {"keyowrd": "bulgaria", "function": ["noun"], "category": "country"},
        {"keyowrd": "burkina faso", "function": ["noun"], "category": "country"},
        {"keyowrd": "burkina", "function": ["noun"], "category": "country"},
        {"keyowrd": "faso", "function": ["noun"], "category": "country"},
        {"keyowrd": "burundi", "function": ["noun"], "category": "country"},
        {"keyowrd": "cambodia", "function": ["noun"], "category": "country"},
        {"keyowrd": "cameroon", "function": ["noun"], "category": "country"},
        {"keyowrd": "canada", "function": ["noun"], "category": "country"},
        {"keyowrd": "cape verde", "function": ["noun"], "category": "country"},
        {"keyowrd": "cayman", "function": ["noun"], "category": "country"},
        {
            "keyowrd": "central african republic",
            "function": ["noun"],
            "category": "country",
        },
        {"keyowrd": "chad", "function": ["noun"], "category": "country"},
        {"keyowrd": "chile", "function": ["noun"], "category": "country"},
        {"keyowrd": "christmas island", "function": ["noun"], "category": "country"},
        {"keyowrd": "colombia", "function": ["noun"], "category": "country"},
        {"keyowrd": "comoros", "function": ["noun"], "category": "country"},
        {"keyowrd": "congo", "function": ["noun"], "category": "country"},
        {"keyowrd": "cook islands", "function": ["noun"], "category": "country"},
        {"keyowrd": 'costa", "rica', "function": ["noun"], "category": "country"},
        {"keyowrd": "cote d'ivoire", "function": ["noun"], "category": "country"},
        {"keyowrd": "d'ivoire", "function": ["noun"], "category": "country"},
        {"keyowrd": "croatia", "function": ["noun"], "category": "country"},
        {"keyowrd": "cuba", "function": ["noun"], "category": "country"},
        {"keyowrd": "curaçao", "function": ["noun"], "category": "country"},
        {"keyowrd": "cyprus", "function": ["noun"], "category": "country"},
        {"keyowrd": "denmark", "function": ["noun"], "category": "country"},
        {"keyowrd": "djibouti", "function": ["noun"], "category": "country"},
        {"keyowrd": "dominica", "function": ["noun"], "category": "country"},
        {"keyowrd": "ecuador", "function": ["noun"], "category": "country"},
        {"keyowrd": "egypt", "function": ["noun"], "category": "country"},
        {"keyowrd": "salvador", "function": ["noun"], "category": "country"},
        {"keyowrd": "england", "function": ["noun"], "category": "country"},
        {"keyowrd": "guinea", "function": ["noun"], "category": "country"},
        {"keyowrd": "eritrea", "function": ["noun"], "category": "country"},
        {"keyowrd": "estonia", "function": ["noun"], "category": "country"},
        {"keyowrd": "eswatini", "function": ["noun"], "category": "country"},
        {"keyowrd": "ethiopia", "function": ["noun"], "category": "country"},
        {"keyowrd": "falkland", "function": ["noun"], "category": "country"},
        {"keyowrd": "faroe", "function": ["noun"], "category": "country"},
        {"keyowrd": "micronesia", "function": ["noun"], "category": "country"},
        {"keyowrd": "fiji", "function": ["noun"], "category": "country"},
        {"keyowrd": "finland", "function": ["noun"], "category": "country"},
        {"keyowrd": "france", "function": ["noun"], "category": "country"},
        {"keyowrd": "guiana", "function": ["noun"], "category": "country"},
        {"keyowrd": "polynesia", "function": ["noun"], "category": "country"},
        {"keyowrd": "gabon", "function": ["noun"], "category": "country"},
        {"keyowrd": "georgia", "function": ["noun"], "category": "country"},
        {"keyowrd": "germany", "function": ["noun"], "category": "country"},
        {"keyowrd": "ghana", "function": ["noun"], "category": "country"},
        {"keyowrd": "gibraltar", "function": ["noun"], "category": "country"},
        {"keyowrd": "greece", "function": ["noun"], "category": "country"},
        {"keyowrd": "greenland", "function": ["noun"], "category": "country"},
        {"keyowrd": "grenada", "function": ["noun"], "category": "country"},
        {"keyowrd": "guadeloupe", "function": ["noun"], "category": "country"},
        {"keyowrd": "guam", "function": ["noun"], "category": "country"},
        {"keyowrd": "guatemala", "function": ["noun"], "category": "country"},
        {"keyowrd": "guernsey", "function": ["noun"], "category": "country"},
        {"keyowrd": "guinea", "function": ["noun"], "category": "country"},
        {"keyowrd": "guinea-bissau", "function": ["noun"], "category": "country"},
        {"keyowrd": "guyana", "function": ["noun"], "category": "country"},
        {"keyowrd": "haiti", "function": ["noun"], "category": "country"},
        {"keyowrd": "honduras", "function": ["noun"], "category": "country"},
        {"keyowrd": "hong-kong", "function": ["noun"], "category": "country"},
        {"keyowrd": "hong kong", "function": ["noun"], "category": "country"},
        {"keyowrd": "hong", "function": ["noun"], "category": "country"},
        {"keyowrd": "kong", "function": ["noun"], "category": "country"},
        {"keyowrd": "hungary", "function": ["noun"], "category": "country"},
        {"keyowrd": "iceland", "function": ["noun"], "category": "country"},
        {"keyowrd": "india", "function": ["noun"], "category": "country"},
        {"keyowrd": "indonesia", "function": ["noun"], "category": "country"},
        {"keyowrd": "iran", "function": ["noun"], "category": "country"},
        {"keyowrd": "iraq", "function": ["noun"], "category": "country"},
        {"keyowrd": "ireland", "function": ["noun"], "category": "country"},
        {"keyowrd": "isle of man", "function": ["noun"], "category": "country"},
        {"keyowrd": "israel", "function": ["noun"], "category": "country"},
        {"keyowrd": "jamaica", "function": ["noun"], "category": "country"},
        {"keyowrd": "japan", "function": ["noun"], "category": "country"},
        {"keyowrd": "jersey", "function": ["noun"], "category": "country"},
        {"keyowrd": "jordan", "function": ["noun"], "category": "country"},
        {"keyowrd": "kazakhstan", "function": ["noun"], "category": "country"},
        {"keyowrd": "kenya", "function": ["noun"], "category": "country"},
        {"keyowrd": "kiribati", "function": ["noun"], "category": "country"},
        {"keyowrd": "kosovo", "function": ["noun"], "category": "country"},
        {"keyowrd": "kuwait", "function": ["noun"], "category": "country"},
        {"keyowrd": "kyrgyzstan", "function": ["noun"], "category": "country"},
        {"keyowrd": "laos", "function": ["noun"], "category": "country"},
        {"keyowrd": "latvia", "function": ["noun"], "category": "country"},
        {"keyowrd": "lebanon", "function": ["noun"], "category": "country"},
        {"keyowrd": "lesotho", "function": ["noun"], "category": "country"},
        {"keyowrd": "liberia", "function": ["noun"], "category": "country"},
        {"keyowrd": "libya", "function": ["noun"], "category": "country"},
        {"keyowrd": "liechtenstein", "function": ["noun"], "category": "country"},
        {"keyowrd": "lithuania", "function": ["noun"], "category": "country"},
        {"keyowrd": "luxembourg", "function": ["noun"], "category": "country"},
        {"keyowrd": "macau", "function": ["noun"], "category": "country"},
        {"keyowrd": "madagascar", "function": ["noun"], "category": "country"},
        {"keyowrd": "madeira", "function": ["noun"], "category": "country"},
        {"keyowrd": "malawi", "function": ["noun"], "category": "country"},
        {"keyowrd": "malaysia", "function": ["noun"], "category": "country"},
        {"keyowrd": "maldives", "function": ["noun"], "category": "country"},
        {"keyowrd": "mali", "function": ["noun"], "category": "country"},
        {"keyowrd": "malta", "function": ["noun"], "category": "country"},
        {"keyowrd": "marshall islands", "function": ["noun"], "category": "country"},
        {"keyowrd": "martinique", "function": ["noun"], "category": "country"},
        {"keyowrd": "mauritania", "function": ["noun"], "category": "country"},
        {"keyowrd": "mauritius", "function": ["noun"], "category": "country"},
        {"keyowrd": "mayotte", "function": ["noun"], "category": "country"},
        {"keyowrd": "mexico", "function": ["noun"], "category": "country"},
        {"keyowrd": "moldova", "function": ["noun"], "category": "country"},
        {"keyowrd": "monaco", "function": ["noun"], "category": "country"},
        {"keyowrd": "mongolia", "function": ["noun"], "category": "country"},
        {"keyowrd": "montenegro", "function": ["noun"], "category": "country"},
        {"keyowrd": "montserrat", "function": ["noun"], "category": "country"},
        {"keyowrd": "morocco", "function": ["noun"], "category": "country"},
        {"keyowrd": "mozambique", "function": ["noun"], "category": "country"},
        {"keyowrd": "myanmar", "function": ["noun"], "category": "country"},
        {"keyowrd": "namibia", "function": ["noun"], "category": "country"},
        {"keyowrd": "nauru", "function": ["noun"], "category": "country"},
        {"keyowrd": "nepal", "function": ["noun"], "category": "country"},
        {"keyowrd": "netherlands", "function": ["noun"], "category": "country"},
        {"keyowrd": "new caledonia", "function": ["noun"], "category": "country"},
        {"keyowrd": "caledonia", "function": ["noun"], "category": "country"},
        {"keyowrd": "new zealand", "function": ["noun"], "category": "country"},
        {"keyowrd": "zealand", "function": ["noun"], "category": "country"},
        {"keyowrd": "nicaragua", "function": ["noun"], "category": "country"},
        {"keyowrd": "niger", "function": ["noun"], "category": "country"},
        {"keyowrd": "nigeria", "function": ["noun"], "category": "country"},
        {"keyowrd": "niue", "function": ["noun"], "category": "country"},
        {"keyowrd": "norfolk island", "function": ["noun"], "category": "country"},
        {"keyowrd": "norfolk", "function": ["noun"], "category": "country"},
        {"keyowrd": "north korea", "function": ["noun"], "category": "country"},
        {"keyowrd": "north macedonia", "function": ["noun"], "category": "country"},
        {"keyowrd": "northern ireland", "function": ["noun"], "category": "country"},
        {
            "keyowrd": "northern mariana islands",
            "function": ["noun"],
            "category": "country",
        },
        {"keyowrd": "norway", "function": ["noun"], "category": "country"},
        {"keyowrd": "oman", "function": ["noun"], "category": "country"},
        {"keyowrd": "pakistan", "function": ["noun"], "category": "country"},
        {"keyowrd": "palau", "function": ["noun"], "category": "country"},
        {"keyowrd": "palestine", "function": ["noun"], "category": "country"},
        {"keyowrd": "panama", "function": ["noun"], "category": "country"},
        {"keyowrd": "papua new guinea", "function": ["noun"], "category": "country"},
        {"keyowrd": "papua", "function": ["noun"], "category": "country"},
        {"keyowrd": "paraguay", "function": ["noun"], "category": "country"},
        {"keyowrd": "peru", "function": ["noun"], "category": "country"},
        {"keyowrd": "philippines", "function": ["noun"], "category": "country"},
        {"keyowrd": "pitcairn islands", "function": ["noun"], "category": "country"},
        {"keyowrd": "poland", "function": ["noun"], "category": "country"},
        {"keyowrd": "puerto rico", "function": ["noun"], "category": "country"},
        {"keyowrd": "qatar", "function": ["noun"], "category": "country"},
        {
            "keyowrd": "republic of the congo",
            "function": ["noun"],
            "category": "country",
        },
        {"keyowrd": "congo", "function": ["noun"], "category": "country"},
        {"keyowrd": "romania", "function": ["noun"], "category": "country"},
        {"keyowrd": "russia", "function": ["noun"], "category": "country"},
        {"keyowrd": "rwanda", "function": ["noun"], "category": "country"},
        {"keyowrd": "réunion", "function": ["noun"], "category": "country"},
        {"keyowrd": "saint barthélemy", "function": ["noun"], "category": "country"},
        {"keyowrd": "saint helena", "function": ["noun"], "category": "country"},
        {
            "keyowrd": "saint kitts and nevis",
            "function": ["noun"],
            "category": "country",
        },
        {"keyowrd": "saint lucia", "function": ["noun"], "category": "country"},
        {"keyowrd": "saint martin", "function": ["noun"], "category": "country"},
        {
            "keyowrd": "saint pierre and miquelon",
            "function": ["noun"],
            "category": "country",
        },
        {
            "keyowrd": 'saint vincent", "grenadines',
            "function": ["noun"],
            "category": "country",
        },
        {"keyowrd": "samoa", "function": ["noun"], "category": "country"},
        {"keyowrd": "san marino", "function": ["noun"], "category": "country"},
        {"keyowrd": "marino", "function": ["noun"], "category": "country"},
        {"keyowrd": "sark", "function": ["noun"], "category": "country"},
        {"keyowrd": "saudi arabia", "function": ["noun"], "category": "country"},
        {"keyowrd": "arabia", "function": ["noun"], "category": "country"},
        {"keyowrd": "scotland", "function": ["noun"], "category": "country"},
        {"keyowrd": "senegal", "function": ["noun"], "category": "country"},
        {"keyowrd": "seychelles", "function": ["noun"], "category": "country"},
        {"keyowrd": "sierra leone", "function": ["noun"], "category": "country"},
        {"keyowrd": "singapore", "function": ["noun"], "category": "country"},
        {"keyowrd": "sint maarten", "function": ["noun"], "category": "country"},
        {"keyowrd": "slovakia", "function": ["noun"], "category": "country"},
        {"keyowrd": "slovenia", "function": ["noun"], "category": "country"},
        {"keyowrd": "solomon islands", "function": ["noun"], "category": "country"},
        {"keyowrd": "somalia", "function": ["noun"], "category": "country"},
        {"keyowrd": "somaliland", "function": ["noun"], "category": "country"},
        {"keyowrd": "south africa", "function": ["noun"], "category": "country"},
        {
            "keyowrd": "south georgia and the south sandwich islands",
            "function": ["noun"],
            "category": "country",
        },
        {"keyowrd": "south korea", "function": ["noun"], "category": "country"},
        {"keyowrd": "korea", "function": ["noun"], "category": "country"},
        {"keyowrd": "south sudan", "function": ["noun"], "category": "country"},
        {"keyowrd": "spain", "function": ["noun"], "category": "country"},
        {"keyowrd": "sri lanka", "function": ["noun"], "category": "country"},
        {"keyowrd": "sudan", "function": ["noun"], "category": "country"},
        {"keyowrd": "suriname", "function": ["noun"], "category": "country"},
        {
            "keyowrd": 'svalbard", "jan mayen islands',
            "function": ["noun"],
            "category": "country",
        },
        {"keyowrd": "sweden", "function": ["noun"], "category": "country"},
        {"keyowrd": "switzerland", "function": ["noun"], "category": "country"},
        {"keyowrd": "syria", "function": ["noun"], "category": "country"},
        {
            "keyowrd": 'são tomé", "príncipe',
            "function": ["noun"],
            "category": "country",
        },
        {"keyowrd": "taiwan", "function": ["noun"], "category": "country"},
        {"keyowrd": "tajikistan", "function": ["noun"], "category": "country"},
        {"keyowrd": "tanzania", "function": ["noun"], "category": "country"},
        {"keyowrd": "thailand", "function": ["noun"], "category": "country"},
        {"keyowrd": "bahamas", "function": ["noun"], "category": "country"},
        {"keyowrd": "gambia", "function": ["noun"], "category": "country"},
        {"keyowrd": "timor-leste", "function": ["noun"], "category": "country"},
        {"keyowrd": "togo", "function": ["noun"], "category": "country"},
        {"keyowrd": "tokelau", "function": ["noun"], "category": "country"},
        {"keyowrd": "tonga", "function": ["noun"], "category": "country"},
        {"keyowrd": 'trinidad", "tobago', "function": ["noun"], "category": "country"},
        {"keyowrd": "tunisia", "function": ["noun"], "category": "country"},
        {"keyowrd": "turkey", "function": ["noun"], "category": "country"},
        {"keyowrd": "turkmenistan", "function": ["noun"], "category": "country"},
        {
            "keyowrd": "turks and caicos islands",
            "function": ["noun"],
            "category": "country",
        },
        {"keyowrd": "caicos", "function": ["noun"], "category": "country"},
        {"keyowrd": "tuvalu", "function": ["noun"], "category": "country"},
        {"keyowrd": "uganda", "function": ["noun"], "category": "country"},
        {"keyowrd": "ukraine", "function": ["noun"], "category": "country"},
        {
            "keyowrd": "united arab emirates",
            "function": ["noun"],
            "category": "country",
        },
        {"keyowrd": "u.a.e.", "function": ["noun"], "category": "country"},
        {"keyowrd": "united kingdom", "function": ["noun"], "category": "country"},
        {"keyowrd": "u.k.", "function": ["noun"], "category": "country"},
        {"keyowrd": "uk", "function": ["noun"], "category": "country"},
        {
            "keyowrd": "united states minor outlying islands",
            "function": ["noun"],
            "category": "country",
        },
        {
            "keyowrd": "united states virgin islands",
            "function": ["noun"],
            "category": "country",
        },
        {
            "keyowrd": "united states of america",
            "function": ["noun"],
            "category": "country",
        },
        {"keyowrd": "u.s.a.", "function": ["noun"], "category": "country"},
        {"keyowrd": "usa", "function": ["noun"], "category": "country"},
        {"keyowrd": "uruguay", "function": ["noun"], "category": "country"},
        {"keyowrd": "uzbekistan", "function": ["noun"], "category": "country"},
        {"keyowrd": "vanuatu", "function": ["noun"], "category": "country"},
        {"keyowrd": "vatican", "function": ["noun"], "category": "country"},
        {"keyowrd": "venezuela", "function": ["noun"], "category": "country"},
        {"keyowrd": "vietnam", "function": ["noun"], "category": "country"},
        {"keyowrd": "wales", "function": ["noun"], "category": "country"},
        {"keyowrd": "wallis", "function": ["noun"], "category": "country"},
        {"keyowrd": "sahara", "function": ["noun"], "category": "country"},
        {"keyowrd": "yemen", "function": ["noun"], "category": "country"},
        {"keyowrd": "zambia", "function": ["noun"], "category": "country"},
        {"keyowrd": "zimbabwe", "function": ["noun"], "category": "country"},
        {"keyowrd": "åland", "function": ["noun"], "category": "country"},
        {"keyowrd": "china", "function": ["noun"], "category": "country"},
        {"keyowrd": "italy", "function": ["noun"], "category": "country"},
        {"keyowrd": "cyprus", "function": ["noun"], "category": "country"},
        {"keyowrd": "portugal", "function": ["noun"], "category": "country"},
        {"keyowrd": "serbia", "function": ["noun"], "category": "country"},
        {"keyowrd": "europa", "function": ["noun"], "category": "continent"},
        {"keyowrd": "european", "function": ["noun"], "category": "nationality"},
        {"keyowrd": "asia", "function": ["noun"], "category": "continent"},
        {"keyowrd": "asian", "function": ["noun"], "category": "nationality"},
        {
            "keyowrd": "afghan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "albanian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "algerian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "american",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "andorran",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "angolan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "antiguans",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "argentinean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "armenian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "australian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "austrian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "azerbaijani",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "bahamian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "bahraini",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "bangladeshi",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "barbadian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "barbudans",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "batswana",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "belarusian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "belgian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "belizean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "beninese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "bhutanese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "bolivian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "bosnian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "brazilian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "british",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "bruneian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "bulgarian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "burkinabe",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "burmese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "burundian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "cambodian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "cameroonian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "canadian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "verdean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "african",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "chadian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "chilean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "chinese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "colombian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "comoran",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "congolese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "costa",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "rican",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "croatian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "cuban",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "cypriot",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "czech",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "danish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "djibouti",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "dominican",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "dutch",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "timorese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "ecuadorean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "egyptian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "emirian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "equatorial",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "eritrean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "estonian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "ethiopian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "fijian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "filipino",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "finnish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "french",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "gabonese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "gambian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "georgian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "german",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "ghanaian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "greek",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "grenadian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "guatemalan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "bissauan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "guinean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "guyanese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "haitian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "herzegovinian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "honduran",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "hungarian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "icelander",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "indian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "indonesian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "iranian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "iraqi",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "irish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "israeli",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "italian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "ivorian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "jamaican",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "japanese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "jordanian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "kazakhstani",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "kenyan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "kittian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "nevisian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "kuwaiti",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "kyrgyz",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "laotian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "latvian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "lebanese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "liberian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "libyan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "liechtensteiner",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "lithuanian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "luxembourger",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "macedonian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "malagasy",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "malawian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "malaysian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "maldivian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "malian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "maltese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "marshallese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "mauritanian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "mauritian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "mexican",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "micronesian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "moldovan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "monacan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "mongolian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "moroccan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "mosotho",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "motswana",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "mozambican",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "namibian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "nauruan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "nepalese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "zealander",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "ni-vanuatu",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "nicaraguan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "nigerian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "nigerien",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "irish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "norwegian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "omani",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "pakistani",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "palauan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "panamanian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "papua",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "guinean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "paraguayan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "peruvian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "polish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "portuguese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "qatari",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "romanian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "russian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "rwandan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "salvadoran",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "samoan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "marinese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "tomean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "saudi",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "scottish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "senegalese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "serbian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "seychellois",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "leonean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "singaporean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "slovakian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "slovenian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "solomon islander",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "somali",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "korean",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "spanish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "lankan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "sudanese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "surinamer",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "swazi",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "swedish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "swiss",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "syrian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "taiwanese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "tajik",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "tanzanian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "thai",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "togolese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "tongan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "trinidadian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "tobagonian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "tunisian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "turkish",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "tuvaluan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "ugandan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "ukrainian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "uruguayan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "uzbekistani",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "venezuelan",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "vietnamese",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "welsh",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "yemenite",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
        {
            "keyowrd": "zambian",
            "function": ["noun", "adjective"],
            "category": "nationality",
        },
    ],
    "ethnicity": [
        {"keyword": "asian", "function": ["noun", "adjective"]},
        {"keyword": "asian indian", "function": ["noun", "adjective"]},
        {"keyword": "african", "function": ["noun", "adjective"]},
        {"keyword": "african-american", "function": ["noun", "adjective"]},
        {"keyword": "afro-caribbean", "function": ["noun", "adjective"]},
        {"keyword": "bangladeshi", "function": ["noun", "adjective"]},
        {"keyword": "black", "function": ["noun", "adjective"]},
        {"keyword": "caucasian", "function": ["noun", "adjective"]},
        {"keyword": "chinese", "function": ["noun", "adjective"]},
        {"keyword": "european", "function": ["noun", "adjective"]},
        {"keyword": "hindu", "function": ["noun", "adjective"]},
        {"keyword": "hispanic", "function": ["noun", "adjective"]},
        {"keyword": "indian", "function": ["noun", "adjective"]},
        {"keyword": "indigenous", "function": ["noun", "adjective"]},
        {"keyword": "irish", "function": ["noun", "adjective"]},
        {"keyword": "native", "function": ["noun", "adjective"]},
        {"keyword": "occidental", "function": ["noun", "adjective"]},
        {"keyword": "oriental", "function": ["noun", "adjective"]},
        {"keyword": "pakistani", "function": ["noun", "adjective"]},
        {"keyword": "south asian", "function": ["noun", "adjective"]},
        {"keyword": "western", "function": ["noun", "adjective"]},
        {"keyword": "white", "function": ["noun", "adjective"]},
        {"keyword": "mixed race", "function": ["noun", "adjective"]},
        {"keyword": "mixed", "function": ["noun", "adjective"]},
    ],
    "religion": [
        {"keyword": "jew", "function": ["noun_singular"], "category": "judaism"},
        {"keyword": "jewish", "function": ["adjective"], "category": "judaism"},
        {"keyword": "jews", "function": ["noun_plural"], "category": "judaism"},
        {"keyword": "judaism", "function": ["noun_singular"], "category": "judaism"},
        {"keyword": "muslim", "function": ["noun_singular", "adjective"], "category": "islam"},
        {"keyword": "muslims", "function": ["noun_plural"], "category": "islam"},
        {"keyword": "moslem", "function": ["noun_singular"], "category": "islam"},
        {"keyword": "moslems", "function": ["noun_plural"], "category": "islam"},
        {"keyword": "islam", "function": ["noun"], "category": "islam"},
        {"keyword": "christ", "function": ["noun_singular"], "category": "christianity"},
        {"keyword": "christian", "function": ["noun_singular"], "category": "christianity"},
        {"keyword": "christianity", "function": ["noun"], "category": "christianity"},
        {"keyword": "christians", "function": ["noun_plural"], "category": "christianity"},
        {"keyword": "buddhism", "function": ["noun"], "category": "buddhism"},
        {"keyword": "buddhist", "function": ["noun_singular"], "category": "buddhism"},
        {"keyword": "buddhists", "function": ["noun_plural"], "category": "buddhism"},
        {"keyword": "hindu", "function": ["noun_singular"], "category": "hinduism"},
        {"keyword": "hindus", "function": ["noun_plural"], "category": "hinduism"},
        {"keyword": "hinduism", "function": ["noun"], "category": "hinduism"},
    ],
    "gender": [
        "female",
        "feminine",
        "woman",
        "women",
        "he",
        "she",
        "they",
        "her",
        "hers",
        "them",
        "their",
        "theirs",
        "themself",
        "theirselves",
        "him",
        "his",
        "himself",
        "herself",
        "mrs.",
        "ms.",
        "miss",
        "madam",
        "lady",
        "ladies",
        "girl",
        "girls",
        "mother",
        "mothers",
        "mom",
        "mommy",
        "mum",
        "moms",
        "ma",
        "aunt",
        "daughter",
        "daughters",
        "wife",
        "wives",
        "grandmother",
        "grandmothers",
        "grandma",
        "grandmas",
        "sister",
        "sisters",
        "sista",
        "sistas",
        "male",
        "mr.",
        "sir",
        "masculine",
        "man",
        "men",
        "bro",
        "bros",
        "guy",
        "guys",
        "boy",
        "boys",
        "father",
        "fathers",
        "dad",
        "dads",
        "daddy",
        "son",
        "sons",
        "husband",
        "husbands",
        "grandfather",
        "grandfathers",
        "grandpa",
        "grandpas",
        "uncle",
        "brother",
        "brothers",
        "transgender",
        "trans",
        "cis",
    ],
    "gendered words": [
        "waiter",
        "waitress",
        "tailor",
        "seamstress",
        "actor",
        "actress",
        "policeman",
        "policewoman",
        "salesman",
        "saleswoman",
        "benefactor",
        "benefactress",
        "conductor",
        "conductress",
        "steward",
        "stewardess",
        "monk",
        "nun",
        "god",
        "goddess",
    ],
}
