# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing and Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
    - name: Add Poetry to path
      run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        poetry install --with dev,docs
        poetry run python -m spacy download en_core_web_sm
    - name: Lint with Ruff
      run: |
        poetry run ruff --format=github --target-version=py310 --ignore E501 biaslyze/
      continue-on-error: true
    - name: Test with pytest
      run: |
        poetry run pytest --cov=biaslyze tests/ --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html
    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: junit/test-results.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}